### ISSUE TITLE
Issue with Running PEARL and Inquiring 

### ISSUE THREAD

**Issue by Kirenwp** [enjeeneer/PEARL#2]
Hi,

I've been attempting to run PEARL, but I've encountered some bugs, such as 
`File "main.py", line 51, in <module>
    action_dict, state_action, last_obs = agent.plan(obs, env,prev_action)
TypeError: plan() takes 3 positional arguments but 4 were given`
or
`  File "main.py", line 72, in <module>
    if (agent.n_steps <= agent.cfg.exploration_steps) and (agent.n_steps > cfg.window):
   ......
  File "C:\Program Files (x86)\anaconda3\envs\pearl\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key exploration_steps
    full_key: exploration_steps
    object_type=dict`

I'm wondering whether these issues are a result of my own actions and  is there currently a smoother-running version available?

By the way, I can not  find a usable version of pymodelica. Do you know how to install it?

Thank you!

**Comment by enjeeneer** [comment]
Hey @Kirenwp, thanks very much for raising this issue and for your interest. Apologies for the slow reply, I haven't prioritised a response. 

These issues are a hangover from uploading this slimed-down version of the codebase for exposition. `prev_action` used to be required in a previous, unpublished exploratory algorithm. The linked PR should fix your issue, let me know if it doesn't.

**Comment by Kirenwp** [comment]
Thank you very much, I also believe it's likely due to version changes. I will look into it.
